Added the git commit all (comall) shorthand

diff --git a/git_createbranch b/git_createbranch
--- a/git_createbranch
+++ b/git_createbranch
@@ -5,6 +5,12 @@ git_createbranch() {
     local branch_name
     local source_branch="develop"
 
+    # Check if the current directory is a Git repository
+    if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
+        echo "Error: Not a Git repository. Exiting."
+        return 1
+    fi
+
     if [ $# -eq 2 ]; then
         source_branch="$1"
         branch_name="$2"
diff --git a/git_switch b/git_switch
--- a/git_switch
+++ b/git_switch
@@ -5,6 +5,12 @@ git_switch() {
   search_string=$1
   branch_index=$2
 
+  # Check if the current directory is a Git repository
+  if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
+      echo "Error: Not a Git repository. Exiting."
+      return 1
+  fi
+
   # Get all branches matching the search string
   branches=$(git branch -r | grep "$search_string")
 
