Various improvements

diff --git a/git_branchhistory b/git_branchhistory
--- a/git_branchhistory
+++ b/git_branchhistory
@@ -2,20 +2,31 @@
 # history
 
 function git_branchhistory() {
+  # Check if the current directory is a Git repository
+  if ! git rev-parse --is-inside-work-tree &>/dev/null; then
+      echo "Error: Not in a valid Git repository. Please switch to a valid Git repository."
+      return 1
+  fi
+
   branches=$(git reflog | grep "checkout" | awk '{print $NF}' | awk '!seen[$0]++' | head -n 10)
-  if [ -z "$1" ]; then
-    index=1
-    echo "$branches" | while read branch; do
-      echo "$index: $branch"
-      index=$((index + 1))
-    done
+  if [ -z "$branches" ]; then
+    echo "No recent branches found. Current branch: $current_branch"
   else
-    branch=$(echo "$branches" | sed -n "${1}p")
-    if [ -n "$branch" ]; then
-      git checkout "$branch"
-      echo "Switched to branch '$branch'"
+    if [ -z "$1" ]; then
+      # If no branches found, display the current branch
+      index=1
+      echo "$branches" | while read branch; do
+        echo "$index: $branch"
+        index=$((index + 1))
+      done
     else
-      echo "Invalid index"
+      branch=$(echo "$branches" | sed -n "${1}p")
+      if [ -n "$branch" ]; then
+        git checkout "$branch"
+        echo "Switched to branch '$branch'"
+      else
+        echo "Invalid index"
+      fi
     fi
   fi
 }
diff --git a/git_commitall b/git_commitall
--- a/git_commitall
+++ b/git_commitall
@@ -10,8 +10,8 @@ function git_commitall() {
     fi
 
     # Check if the current directory is a Git repository
-    if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
-        echo "Error: Not a Git repository. Exiting."
+    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
+        echo "Error: Not in a valid Git repository. Please switch to a valid Git repository."
         return 1
     fi
 
diff --git a/git_commitmessages b/git_commitmessages
--- a/git_commitmessages
+++ b/git_commitmessages
@@ -3,18 +3,34 @@
 
 function git_commitmessages() {
     # Check if the current directory is a Git repository
-    if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
-        echo "Error: Not a Git repository. Exiting."
+    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
+        echo "Error: Not in a valid Git repository. Please switch to a valid Git repository."
         return 1
     fi
 
     # Get the current branch name
     current_branch=$(git symbolic-ref --short HEAD)
 
-    # Find the commit where the branch was created by looking for the merge-base with the main branch
-    # Replace 'main' with the default branch of your repository if it's different
-    base_commit=$(git merge-base $current_branch master)
+    # Check if 'master' branch exists
+    if git show-ref --quiet refs/heads/master; then
+        base_branch="master"
+    # Check if 'main' branch exists if 'master' doesn't
+    elif git show-ref --quiet refs/heads/main; then
+        base_branch="main"
+    else
+        echo "Error: Neither 'master' nor 'main' branch exists."
+        return 1
+    fi
 
-    # List commit messages from the current branch (excluding specified patterns), starting from the base commit
-    git log --pretty=format:"- %s" --grep="^\(WIP\|Opt\|Optimization\):" --invert-grep --no-merges --first-parent $base_commit..$current_branch
+    # If current branch is the same as the base branch, show all commit messages
+    if [ "$current_branch" = "$base_branch" ]; then
+        echo "Current branch is '$base_branch'. Showing all commit messages:"
+        git log --pretty=format:"- %s" --grep="^\(WIP\|Opt\|Optimization\):" --invert-grep --no-merges --first-parent
+    else
+        # Find the commit where the branch was created by looking for the merge-base with the base branch
+        base_commit=$(git merge-base $current_branch $base_branch)
+
+        # List commit messages from the current branch (excluding specified patterns), starting from the base commit
+        git log --pretty=format:"- %s" --grep="^\(WIP\|Opt\|Optimization\):" --invert-grep --no-merges --first-parent $base_commit..$current_branch
+    fi
 }
diff --git a/git_createbranch b/git_createbranch
--- a/git_createbranch
+++ b/git_createbranch
@@ -6,8 +6,8 @@ git_createbranch() {
     local source_branch="develop"
 
     # Check if the current directory is a Git repository
-    if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
-        echo "Error: Not a Git repository. Exiting."
+    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
+        echo "Error: Not in a valid Git repository. Please switch to a valid Git repository."
         return 1
     fi
 
@@ -18,12 +18,6 @@ git_createbranch() {
         branch_name="$1"
     else
         echo "Usage: createbranch <source_branch> <branch_name> or createbranch <branch_name>"
-        return 1
-    fi
-
-    # Check if the current directory is a Git repository
-    if ! git rev-parse --is-inside-work-tree &>/dev/null; then
-        echo "Error: Not in a valid Git repository. Please switch to a valid Git repository."
         return 1
     fi
 
diff --git a/git_switch b/git_switch
--- a/git_switch
+++ b/git_switch
@@ -6,8 +6,14 @@ git_switch() {
   branch_index=$2
 
   # Check if the current directory is a Git repository
-  if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
-      echo "Error: Not a Git repository. Exiting."
+  if ! git rev-parse --is-inside-work-tree &>/dev/null; then
+      echo "Error: Not in a valid Git repository. Please switch to a valid Git repository."
+      return 1
+  fi
+
+  # Check if there are any changes
+  if [[ -n "$(git status --porcelain)" ]]; then
+      echo "Error: There are uncommitted changes. Please commit, stash, or revert the changes first."
       return 1
   fi
 
